import type { Product } from "@/lib/types";

export const products: Product[] = [
  { name: "7EI", family: "EI", center: '3/32"', desc: "Smallest EI lamination" },
  { name: "21EI", family: "EI", center: '21/64"', desc: "Small transformer core" },
  { name: "25EI", family: "EI", center: '3/32" to 1/4"', desc: "Common audio transformer" },
  { name: "25HEI", family: "EI", center: '1/4"', desc: "Half-size variant" },
  { name: "27EI", family: "EI", center: '27/64"', desc: "Mid-range EI" },
  { name: "29EI", family: "EI", center: '29/64"', desc: "Mid-range EI" },
  { name: "50EI", family: "EI", center: '1/2"', desc: "Popular mid-size" },
  { name: "75EI", family: "EI", center: '3/4"', desc: "Common power transformer" },
  { name: "75HSEI", family: "EI", center: '3/4"', desc: "Half-size variant" },
  { name: "87HEI", family: "EI", center: '7/8"', desc: "Large format" },
  { name: "094EI", family: "EI", center: '15/16"', desc: "Near 1-inch core" },
  { name: "100EI", family: "EI", center: '1"', desc: "Standard 1-inch" },
  { name: "125EI", family: "EI", center: '1-1/4"', desc: "Large power transformer" },
  { name: "186EI", family: "EI", center: '1-13/16"', desc: "Heavy duty" },
  { name: "187EI", family: "EI", center: '1-7/8"', desc: "Heavy duty" },
  { name: "188EI", family: "EI", center: '1-7/8"', desc: "Heavy duty" },
  { name: "201EI", family: "EI", center: '2"', desc: "Extra large" },
  { name: "375EI", family: "EI", center: '3-3/4"', desc: "Industrial scale" },
  { name: "625EI", family: "EI", center: '6-1/4"', desc: "Largest EI offering" },
  { name: "2425EE", family: "EE", center: '1/4"', desc: "Small EE core" },
  { name: "2425GE", family: "EE", center: '1/4"', desc: "GE variant" },
  { name: "2627EE", family: "EE", center: '3/8"', desc: "Mid-range EE" },
  { name: "2638EE", family: "EE", center: '3/8"', desc: "Extended window" },
  { name: "2738EE", family: "EE", center: '3/8"', desc: "Extended window" },
  { name: "2829EE", family: "EE", center: '7/16"', desc: "Mid-range EE" },
  { name: "3031EE", family: "EE", center: '1/2"', desc: "Standard EE" },
  { name: "3233EE", family: "EE", center: '9/16"', desc: "Large EE" },
  { name: "186-187EE", family: "EE", center: '1-7/8"', desc: "Heavy duty EE" },
  { name: "186-188EE", family: "EE", center: '1-7/8"', desc: "Heavy duty EE" },
  { name: "187-188EE", family: "EE", center: '1-7/8"', desc: "Heavy duty EE" },
  { name: "7L", family: "L", center: '7/32"', desc: "Small L-shape" },
  { name: "13L", family: "L", center: '13/32"', desc: "Mid L-shape" },
  { name: "31L", family: "L", center: '31/64"', desc: "Standard L" },
  { name: "50L", family: "L", center: '1/2"', desc: "Common L" },
  { name: "101L", family: "L", center: '1"', desc: "Large L" },
  { name: "103LM", family: "L", center: '1"', desc: "Modified L" },
  { name: "141L", family: "L", center: '1-13/32"', desc: "Extra large L" },
  { name: "188L", family: "L", center: '1-7/8"', desc: "Heavy duty L" },
  { name: "750L", family: "L", center: '7-1/2"', desc: "Largest L offering" },
  { name: "1DU", family: "DU", center: '1/4"', desc: "Small DU core" },
  { name: "18DU", family: "DU", center: '9/32"', desc: "Standard DU" },
  { name: "25DU", family: "DU", center: '1/4"', desc: "Quarter-inch DU" },
  { name: "26DU", family: "DU", center: '3/8"', desc: "Mid-range DU" },
  { name: "37HDU", family: "DU", center: '3/8"', desc: "Half DU" },
  { name: "50DU", family: "DU", center: '1/2"', desc: "Standard half-inch" },
  { name: "63DU", family: "DU", center: '5/8"', desc: "Mid-large DU" },
  { name: "87DU", family: "DU", center: '7/8"', desc: "Large DU" },
  { name: "124DU", family: "DU", center: '1-1/4"', desc: "Extra large DU" },
  { name: "250U", family: "DU", center: '2-1/2"', desc: "Largest U core" },
  { name: "12F", family: "F", center: '3/16"', desc: "Small F-shape" },
  { name: "14F", family: "F", center: '7/32"', desc: "Standard F" },
  { name: "20F", family: "F", center: '5/16"', desc: "Mid F" },
  { name: "094F", family: "F", center: '15/16"', desc: "Large F" },
  { name: "219F", family: "F", center: '2-3/16"', desc: "Heavy F" },
  { name: "21FB", family: "F", center: '5/16"', desc: "FB variant" },
  { name: "51FB", family: "F", center: '1/2"', desc: "FB mid-size" },
  { name: "2627FB", family: "F", center: '3/8"', desc: "FB standard" },
  { name: "2829FB", family: "F", center: '7/16"', desc: "FB standard" },
  { name: "50FG", family: "F", center: '1/2"', desc: "FG variant" },
  { name: "2425FG", family: "F", center: '1/4"', desc: "FG small" },
  { name: "187FM", family: "F", center: '1-7/8"', desc: "FM variant" },
  { name: "10LE", family: "LE", center: '5/32"', desc: "Small LE" },
  { name: "63LE", family: "LE", center: '5/8"', desc: "Mid LE" },
  { name: "185LE", family: "LE", center: '1-13/16"', desc: "Large LE" },
  { name: "187LE", family: "LE", center: '1-7/8"', desc: "Large LE" },
  { name: "195LE", family: "LE", center: '1-15/16"', desc: "Large LE" },
  { name: "2425LE", family: "LE", center: '1/4"', desc: "Small LE" },
  { name: "2627LE", family: "LE", center: '3/8"', desc: "Standard LE" },
  { name: "3233LE", family: "LE", center: '9/16"', desc: "Mid LE" },
  { name: "3333LE", family: "LE", center: '9/16"', desc: "Mid LE" },
  { name: "31UI", family: "LE", center: '31/64"', desc: "UI type" },
  { name: "50UI", family: "LE", center: '1/2"', desc: "UI standard" },
  { name: "375HUI", family: "LE", center: '3-3/4"', desc: "Heavy UI" },
];
